"""Kraken error codes with confirmed message text (sourced from developer.pwl.kraken.tech)."""

from __future__ import annotations

from typing import TypedDict


class KrakenErrorDetail(TypedDict):
    code: str
    error_type: str
    trigger: str
    message: str
    category: str
    migration_phase: str  # pre_migration | at_load | post_load | operational
    migration_relevance: str  # high | medium | low | none
    owner_role: str
    is_blocker: bool


# Confirmed entries from kraken-error-codes-reference.md §2
DETAILED_ENTRIES: list[KrakenErrorDetail] = [
    {
        "code": "KT-CT-10001",
        "error_type": "VALIDATION",
        "trigger": "Creating a contract that overlaps an existing one for the same party",
        "message": "Party is already under contract.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10003",
        "error_type": "NOT_FOUND",
        "trigger": "Contract lookup failed",
        "message": "Contract not found.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10005",
        "error_type": "VALIDATION",
        "trigger": "Neither identifier nor account number supplied when searching for a contract",
        "message": "Missing required parameter: either identifier or accountNumber must be provided.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10006",
        "error_type": "NOT_FOUND",
        "trigger": "Account lookup failed",
        "message": "Account not found.",
        "category": "account_business_migration",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10007",
        "error_type": "APPLICATION",
        "trigger": "Contract termination failed for an internal reason",
        "message": "Unable to terminate contract.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10008",
        "error_type": "APPLICATION",
        "trigger": "An action attempted on a contract that has an active journey in progress",
        "message": "The contract is currently undergoing an active journey.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10009",
        "error_type": "VALIDATION",
        "trigger": "A supplied contract term doesn't match the expected format",
        "message": "Provided term term is not of the valid format.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10010",
        "error_type": "VALIDATION",
        "trigger": "Two terms of the same type supplied in one term set",
        "message": "Duplicate term type found in the provided term set.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10011",
        "error_type": "APPLICATION",
        "trigger": "Varying contract terms failed internally",
        "message": "Unable to vary contract terms.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10012",
        "error_type": "APPLICATION",
        "trigger": "A contract variation would breach the contract",
        "message": "Contract variation implies breach.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10013",
        "error_type": "VALIDATION",
        "trigger": "Termination date requested is after the contract's end date",
        "message": "Requested termination date is invalid.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10015",
        "error_type": "VALIDATION",
        "trigger": "Supply point termination context couldn't be serialized",
        "message": "Supply point termination context is not serializable.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "medium",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10017",
        "error_type": "NOT_FOUND",
        "trigger": "Contract journey lookup failed",
        "message": "The contract journey could not be found.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10018",
        "error_type": "VALIDATION",
        "trigger": "Invalid contract subject specification",
        "message": "The provided contract subject is invalid.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10019",
        "error_type": "APPLICATION",
        "trigger": "Creating a contract would itself breach it",
        "message": "Contract creation implies breach.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10020",
        "error_type": "VALIDATION",
        "trigger": "Malformed contract-party payload",
        "message": "The provided contract party payload is invalid.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10021",
        "error_type": "NOT_FOUND",
        "trigger": "Business lookup failed",
        "message": "Business not found.",
        "category": "account_business_migration",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10022",
        "error_type": "VALIDATION",
        "trigger": "Action attempted on an already-terminated contract",
        "message": "Contract already terminated.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10023",
        "error_type": "VALIDATION",
        "trigger": "Action attempted on an already-revoked contract",
        "message": "Contract is already revoked.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "medium",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10024",
        "error_type": "VALIDATION",
        "trigger": "Action attempted on an expired contract",
        "message": "Contract already expired.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10025",
        "error_type": "VALIDATION",
        "trigger": "Action attempted on a contract that hasn't started",
        "message": "Contract has not started yet.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10026",
        "error_type": "VALIDATION",
        "trigger": "Actualizing the contract would breach it",
        "message": "Contract actualization implies breach.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10027",
        "error_type": "VALIDATION",
        "trigger": "Termination blocked because a supplier-switch is already in progress",
        "message": "There is an ongoing provider switch.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10028",
        "error_type": "VALIDATION",
        "trigger": "Agreements supplied span more than one market",
        "message": "Contract market mismatch.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10029",
        "error_type": "VALIDATION",
        "trigger": "Contract query submitted with no filters at all",
        "message": "Missing contract filters.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "low",
        "owner_role": "migration_engineer",
        "is_blocker": False,
    },
    {
        "code": "KT-CT-10030",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "Filtering contracts by subject isn't implemented yet",
        "message": "Filter by subject is not implemented.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "low",
        "owner_role": "migration_engineer",
        "is_blocker": False,
    },
    {
        "code": "KT-CT-10031",
        "error_type": "VALIDATION",
        "trigger": "Contract query supplied both/neither of account+business party filters",
        "message": "Invalid party filter.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "medium",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10032",
        "error_type": "VALIDATION",
        "trigger": "Action attempted on a contract that's already started (when it shouldn't be)",
        "message": "Contract has already started.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "medium",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10033",
        "error_type": "VALIDATION",
        "trigger": "A specified term failed to save",
        "message": "Unable to save term.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10034",
        "error_type": "APPLICATION",
        "trigger": "Contract journey type not recognized",
        "message": "Unknown contract journey type.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10035",
        "error_type": "APPLICATION",
        "trigger": "Tried to process a contract journey that isn't active",
        "message": "Cannot process a non-active contract journey.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10036",
        "error_type": "APPLICATION",
        "trigger": "No manager configured to process this contract journey type",
        "message": "The contract journey manager is not found.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10037",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "Contract-notes feature toggled off for this client",
        "message": "Contract notes feature is disabled.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "low",
        "owner_role": "migration_engineer",
        "is_blocker": False,
    },
    {
        "code": "KT-CT-10038",
        "error_type": "VALIDATION",
        "trigger": "Note-reason slug doesn't match any configured reason",
        "message": "Contract note reason not found.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "low",
        "owner_role": "mapping_lead",
        "is_blocker": False,
    },
    {
        "code": "KT-CT-10039",
        "error_type": "VALIDATION",
        "trigger": "Mutation called with none of its (individually optional) affected fields",
        "message": "At least one of the affected fields must be provided.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10040",
        "error_type": "APPLICATION",
        "trigger": "Contract rescission failed internally",
        "message": "Unable to rescind contract.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10041",
        "error_type": "VALIDATION",
        "trigger": "Action attempted on an already-rescinded contract",
        "message": "Contract is already rescinded.",
        "category": "contracts_agreements",
        "migration_phase": "operational",
        "migration_relevance": "medium",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10042",
        "error_type": "VALIDATION",
        "trigger": "Supplied agreements already belong to a different contract",
        "message": "One or more agreements are already attached to a different contract.",
        "category": "contracts_agreements",
        "migration_phase": "at_load",
        "migration_relevance": "high",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10043",
        "error_type": "VALIDATION",
        "trigger": "Neither an account-contract nor business-contract identifier supplied",
        "message": "At least one contract identifier must be provided.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10044",
        "error_type": "VALIDATION",
        "trigger": "Termination date requested is on/before the contract start date",
        "message": "Termination date must be after the contract start date.",
        "category": "contracts_agreements",
        "migration_phase": "pre_migration",
        "migration_relevance": "high",
        "owner_role": "mapping_lead",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10201",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "Auto top-up feature disabled for this client",
        "message": "Endpoint disabled.",
        "category": "auto_topup_prepay",
        "migration_phase": "at_load",
        "migration_relevance": "none",
        "owner_role": "migration_engineer",
        "is_blocker": False,
    },
    {
        "code": "KT-CT-10202",
        "error_type": "VALIDATION",
        "trigger": "Device ID supplied doesn't match any device",
        "message": "Invalid data.",
        "category": "auto_topup_prepay",
        "migration_phase": "pre_migration",
        "migration_relevance": "low",
        "owner_role": "metering",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10203",
        "error_type": "VALIDATION",
        "trigger": "Auto top-up attempted on a non-prepay device",
        "message": "Invalid data.",
        "category": "auto_topup_prepay",
        "migration_phase": "pre_migration",
        "migration_relevance": "low",
        "owner_role": "metering",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10204",
        "error_type": "VALIDATION",
        "trigger": "Top-up amount below the configured minimum",
        "message": "Invalid data.",
        "category": "auto_topup_prepay",
        "migration_phase": "pre_migration",
        "migration_relevance": "low",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10205",
        "error_type": "NOT_FOUND",
        "trigger": "No active auto-top-up config matches the account/device pair",
        "message": "Active auto top-up config not found.",
        "category": "auto_topup_prepay",
        "migration_phase": "at_load",
        "migration_relevance": "low",
        "owner_role": "billing_ops",
        "is_blocker": False,
    },
    {
        "code": "KT-CT-10301",
        "error_type": "VALIDATION",
        "trigger": "Leave-supplier process couldn't be started (validation failure)",
        "message": "Unable to instigate leave supplier process.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10302",
        "error_type": "NOT_FOUND",
        "trigger": "Invalid reference for a leave-supplier process",
        "message": "Invalid data.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "medium",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10303",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "PrepareAccount mutation disabled in this environment",
        "message": "Mutation not enabled in this environment.",
        "category": "leave_supplier_switching",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10304",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "Leave-supplier mutations disabled in this environment",
        "message": "Mutation not enabled in this environment.",
        "category": "leave_supplier_switching",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10305",
        "error_type": "APPLICATION",
        "trigger": "Can't cancel leave-supplier process — market actions are no longer cancellable",
        "message": "Failed to cancel leave supplier process - market actions are no longer cancellable.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10306",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "Cancellation workflow for leave-supplier process isn't configured",
        "message": "Failed to cancel leave supplier process - the cancellation workflow has not been configured.",
        "category": "leave_supplier_switching",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10307",
        "error_type": "APPLICATION",
        "trigger": "Cancelling the underlying market actions failed",
        "message": "Failed to cancel leave supplier process - failed to cancel market actions.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10308",
        "error_type": "APPLICATION",
        "trigger": "Generic leave-supplier cancellation failure",
        "message": "Failed to cancel leave supplier process.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10309",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "Leave-supplier update service not enabled",
        "message": "Failed to update leave supplier process - the service is not enabled.",
        "category": "leave_supplier_switching",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10310",
        "error_type": "APPLICATION",
        "trigger": "Process status doesn't allow updates right now",
        "message": "Failed to update leave supplier process. The process status is not in updatable status.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10311",
        "error_type": "APPLICATION",
        "trigger": "Process status doesn't allow cancellation right now",
        "message": "Failed to cancel leave supplier process. The process status is not in cancellable status.",
        "category": "leave_supplier_switching",
        "migration_phase": "operational",
        "migration_relevance": "high",
        "owner_role": "billing_ops",
        "is_blocker": True,
    },
    {
        "code": "KT-CT-10312",
        "error_type": "SERVICE_AVAILABILITY",
        "trigger": "Enrollment mutation disabled in this environment",
        "message": "Mutation not enabled in this environment.",
        "category": "enrollment",
        "migration_phase": "at_load",
        "migration_relevance": "medium",
        "owner_role": "migration_engineer",
        "is_blocker": True,
    },
]
